KutuphaneProje/Controllers/KitapTuruController.cs
using KutuphaneProje.Models;
using KutuphaneProje.Utility;
using Microsoft.AspNetCore.Mvc;

namespace KutuphaneProje.Controllers
{
	public class KitapTuruController : Controller
	{
		private readonly IKitapTuruRepository _kitapTuruRepository;//dependncy injection

		public KitapTuruController(IKitapTuruRepository context)
		{
			_kitapTuruRepository = context;
		}

		public IActionResult Index()
		{
			List<KitapTuru>objKitapTuruList= _kitapTuruRepository.GetAll().ToList();
			return View(objKitapTuruList);
		}

		public IActionResult Ekle() 
		{ 
			return View();
		}

		[HttpPost]
		public IActionResult Ekle(KitapTuru kitapTuru)
		{
			if (ModelState.IsValid) //Modelden gelen verilerin doğru olup olmadıgını kontrol ediyorum
			{
				_kitapTuruRepository.Ekle(kitapTuru);
				_kitapTuruRepository.Kaydet(); // SaveChanges() yapmazsak bilgiler veritabanına eklenmez.
				TempData["basarili"] = "Yeni Kitap Türü Başarıyla Oluşturuldu! ";
				return RedirectToAction("Index");
			}
			return View();
		}
		public IActionResult Guncelle(int? id)
		{
			if(id== null || id == 0) 
			{
				return NotFound();
			}
			KitapTuru? kitapTuruVt= _kitapTuruRepository.Get(u=>u.Id==id); //Expression<Func<T, bool>> filtre
			if (kitapTuruVt == null) 
			{
				return NotFound();
			}
			return View(kitapTuruVt);
		}

		[HttpPost]
		public IActionResult Guncelle(KitapTuru kitapTuru)
		{
			if (ModelState.IsValid) //Modelden gelen verilerin doğru olup olmadıgını kontrol ediyorum
			{
				_kitapTuruRepository.Guncelle(kitapTuru);
				_kitapTuruRepository.Kaydet(); // SaveChanges() yapmazsak bilgiler veritabanına eklenmez.
				TempData["basarili"] = "Yeni Kitap Türü Başarıyla Güncellendi! ";
				return RedirectToAction("Index");
			}
			return View();
		}

		public IActionResult Sil(int? id)
		{
			if (id == null || id == 0)
			{
				return NotFound();
			}
			KitapTuru? kitapTuruVt = _kitapTuruRepository.Get(u => u.Id == id);
			if (kitapTuruVt == null)
			{
				return NotFound();
			}
			return View(kitapTuruVt);
		}

		[HttpPost, ActionName("Sil")]
		public IActionResult SilPost(int? id)
		{
			KitapTuru? kitapTuru = _kitapTuruRepository.Get(u => u.Id == id);
			if (kitapTuru==null)
			{
				return NotFound();
			}
			_kitapTuruRepository.Sil(kitapTuru);
			_kitapTuruRepository.Kaydet();
			TempData["basarili"] = "Kayıt Silme İşlemi Başarılı! ";
			return RedirectToAction("Index");
		}
	}
}

KutuphaneProje/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - KutuphaneProje</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/KutuphaneProje.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-primary border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">KutuphaneProje</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link " asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link " asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link " asp-area="" asp-controller="KitapTuru" asp-action="Index">Kitap Türü</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - KutuphaneProje - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>